name: Build and Run Puppeteer Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for Puppeteer and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            git \
            python3 \
            python3-venv \
            gnupg2 \
            libnss3 \
            libxss1 \
            libgconf-2-4 \
            libx11-xcb1 \
            libxcomposite1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libnspr4 \
            libxrandr2 \
            libxshmfence1 \
            libgtk-3-0 \
            fonts-liberation \
            libappindicator3-1 \
            libx11-dev \
            libxrender-dev

      - name: Clone repository
        run: git clone https://github.com/d4rk5id3r/wordpress-plugins

      - name: Unzip and navigate to directory
        run: |
          cd wordpress-plugins
          unzip wordpress-plugin-download-main.zip

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Create Python virtual environment and install dependencies
        run: |
          cd wordpress-plugins/wordpress-plugin-download-main
          python3 -m venv wordpress-plugin-grep
          . wordpress-plugin-grep/bin/activate
          pip install -r requirements.txt
          python run.py -f

      -name: Change Directory to WordPress Extracted Plugins
        run: ls    

      - name: Run ripgrep on Linux platforms
        run: |
          rg --no-heading "echo.*\$_GET" | grep ".php:" | grep -v -e "(GET" -e "esc" -e "admin_url" -e "(int)" -e "htmlentities" > report.txt

      - name: Set up Git configuration
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Report Generated 🌟"
          git push https://d4rk5id3r:${{ secrets.TOKEN }}@github.com/d4rk5id3r/report.git main

      - name: Run the application
        run: node server.js  # Replace 'server.js' with your script name
